package test

import (
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/goesm-dev/goesm/internal/build"
	"github.com/goesm-dev/goesm/internal/lower"
)

// tscConfig is the strictest common setup a consumer of goesm's TypeScript
// may use: strict mode, imports with .ts extensions, verbatimModuleSyntax
// and erasableSyntaxOnly (the output runs under type-stripping runtimes).
const tscConfig = `{
  "compilerOptions": {
    "target": "es2022",
    "module": "esnext",
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "noEmit": true,
    "strict": true,
    "verbatimModuleSyntax": true,
    "erasableSyntaxOnly": true,
    "lib": ["es2022", "dom"]
  },
  "include": ["**/*.ts"]
}
`

// consumer uses exported Go APIs from TypeScript: the declared types must
// be the Go signatures (not any), so wrong uses are type errors.
const consumer = `import * as cart from "./example.com/examples/cart.ts";
import * as workers from "./example.com/examples/workers.ts";

const rt = cart.$runtime;
const items = rt.sliceLit([new cart.Item("apple", 120, 3)]);
const total: number = cart.Total(items);
const discounted: number = cart.Discount(total, 15);
const sum: Promise<number> = workers.SumSquares(10, 2);
const square: number = workers.Square(3);
export { discounted, sum, square };

// @ts-expect-error a string is not a []Item
cart.Total("apple");
// @ts-expect-error Item has three fields
new cart.Item("apple", 120);
// @ts-expect-error SumSquares blocks, so it returns a Promise
const notPromise: number = workers.SumSquares(10, 2);
export { notPromise };
`

// TestTSC type-checks the TypeScript goesm emits (fixtures, examples and
// the runtime) with tsc (pinned in test/package.json) in strict mode, and
// checks that exported Go APIs carry their Go types for TypeScript callers.
// It is skipped when tsc is not installed, unless GOESM_REQUIRE_TOOLS is set
// (as in CI).
func TestTSC(t *testing.T) {
	bin, _ := filepath.Abs(filepath.Join("node_modules", ".bin", "tsc"))
	if _, err := os.Stat(bin); err != nil {
		if os.Getenv("GOESM_REQUIRE_TOOLS") != "" {
			t.Fatalf("tsc is not installed: run npm ci in test/")
		}
		t.Skip("tsc is not installed (run npm ci in test/)")
	}
	out := t.TempDir()
	examples, _ := filepath.Abs(filepath.Join("..", "examples"))
	for _, tg := range []struct{ dir, pattern string }{
		{testdata("example"), "./main"},
		{testdata("semantics"), "./basics"},
		{testdata("semantics"), "./complexnum"},
		{testdata("semantics"), "./conformance"},
		{testdata("semantics"), "./generics"},
		{testdata("semantics"), "./goroutines"},
		{testdata("semantics"), "./int64s"},
		{testdata("semantics"), "./panics"},
		{testdata("semantics"), "./stdlibuse"},
		{testdata("programs"), "./pipe"},
		{testdata("programs"), "./stdio"},
		{testdata("programs"), "./ifacevalues"},
		{testdata("programs"), "./condwait"},
		{testdata("programs"), "./lockforms"},
		{testdata("programs"), "./goexitmain"},
		{testdata("programs"), "./initpanic"},
		{testdata("programs"), "./fmtverbs"},
		{testdata("programs"), "./reflection"},
		{testdata("programs"), "./jsoncodec"},
		{testdata("programs"), "./timers"},
		{testdata("programs"), "./mathfuncs"},
		{testdata("programs"), "./jsnames"},
		{examples, "./cart"},
		{examples, "./textstats"},
		{examples, "./workers"},
	} {
		l, err := build.Lower(tg.dir, []string{tg.pattern})
		if err != nil {
			t.Fatalf("goesm %s: %v", tg.pattern, err)
		}
		if err := build.WriteTS(out, l.Mods); err != nil {
			t.Fatal(err)
		}
	}
	// The generated files turn type checking off for the projects that
	// import them (lower.NoCheck); here it stays on.
	err := filepath.WalkDir(out, func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(p, ".ts") {
			return err
		}
		src, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		if !strings.Contains(string(src), lower.NoCheck) {
			return fmt.Errorf("%s does not have the @ts-nocheck header", p)
		}
		return os.WriteFile(p, []byte(strings.Replace(string(src), lower.NoCheck, "", 1)), 0o644)
	})
	if err != nil {
		t.Fatal(err)
	}
	for name, src := range map[string]string{"tsconfig.json": tscConfig, "consumer.ts": consumer} {
		if err := os.WriteFile(filepath.Join(out, name), []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command(bin, "-p", out)
	res, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("tsc reported errors in TypeScript generated by goesm: %v\n%s", err, res)
	}
}
