// Code generated by compare/js/gen-utility.mjs from tailwindcss 4.3.3; DO NOT EDIT.

package utility

const version = "4.3.3"

// staticTable lists the static utilities: name|nodes, where nodes are
// separated by ; and are property:value, @--name,initial-value,syntax for an
// @property rule, or &selector{nodes} for a nested rule.
const staticTable = `sr-only|position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;border-width:0
not-sr-only|position:static;width:auto;height:auto;padding:0;margin:0;overflow:visible;clip-path:none;white-space:normal
pointer-events-none|pointer-events:none
pointer-events-auto|pointer-events:auto
visible|visibility:visible
invisible|visibility:hidden
collapse|visibility:collapse
static|position:static
fixed|position:fixed
absolute|position:absolute
relative|position:relative
sticky|position:sticky
inset-auto|inset:auto
inset-full|inset:100%
-inset-full|inset:-100%
-inset-px|inset:-1px
inset-px|inset:1px
inset-x-auto|inset-inline:auto
inset-x-full|inset-inline:100%
-inset-x-full|inset-inline:-100%
-inset-x-px|inset-inline:-1px
inset-x-px|inset-inline:1px
inset-y-auto|inset-block:auto
inset-y-full|inset-block:100%
-inset-y-full|inset-block:-100%
-inset-y-px|inset-block:-1px
inset-y-px|inset-block:1px
inset-s-auto|inset-inline-start:auto
inset-s-full|inset-inline-start:100%
-inset-s-full|inset-inline-start:-100%
-inset-s-px|inset-inline-start:-1px
inset-s-px|inset-inline-start:1px
inset-e-auto|inset-inline-end:auto
inset-e-full|inset-inline-end:100%
-inset-e-full|inset-inline-end:-100%
-inset-e-px|inset-inline-end:-1px
inset-e-px|inset-inline-end:1px
inset-bs-auto|inset-block-start:auto
inset-bs-full|inset-block-start:100%
-inset-bs-full|inset-block-start:-100%
-inset-bs-px|inset-block-start:-1px
inset-bs-px|inset-block-start:1px
inset-be-auto|inset-block-end:auto
inset-be-full|inset-block-end:100%
-inset-be-full|inset-block-end:-100%
-inset-be-px|inset-block-end:-1px
inset-be-px|inset-block-end:1px
top-auto|top:auto
top-full|top:100%
-top-full|top:-100%
-top-px|top:-1px
top-px|top:1px
right-auto|right:auto
right-full|right:100%
-right-full|right:-100%
-right-px|right:-1px
right-px|right:1px
bottom-auto|bottom:auto
bottom-full|bottom:100%
-bottom-full|bottom:-100%
-bottom-px|bottom:-1px
bottom-px|bottom:1px
left-auto|left:auto
left-full|left:100%
-left-full|left:-100%
-left-px|left:-1px
left-px|left:1px
isolate|isolation:isolate
isolation-auto|isolation:auto
float-start|float:inline-start
float-end|float:inline-end
float-right|float:right
float-left|float:left
float-none|float:none
clear-start|clear:inline-start
clear-end|clear:inline-end
clear-right|clear:right
clear-left|clear:left
clear-both|clear:both
clear-none|clear:none
m-auto|margin:auto
-m-px|margin:-1px
m-px|margin:1px
mx-auto|margin-inline:auto
-mx-px|margin-inline:-1px
mx-px|margin-inline:1px
my-auto|margin-block:auto
-my-px|margin-block:-1px
my-px|margin-block:1px
ms-auto|margin-inline-start:auto
-ms-px|margin-inline-start:-1px
ms-px|margin-inline-start:1px
me-auto|margin-inline-end:auto
-me-px|margin-inline-end:-1px
me-px|margin-inline-end:1px
mbs-auto|margin-block-start:auto
-mbs-px|margin-block-start:-1px
mbs-px|margin-block-start:1px
mbe-auto|margin-block-end:auto
-mbe-px|margin-block-end:-1px
mbe-px|margin-block-end:1px
mt-auto|margin-top:auto
-mt-px|margin-top:-1px
mt-px|margin-top:1px
mr-auto|margin-right:auto
-mr-px|margin-right:-1px
mr-px|margin-right:1px
mb-auto|margin-bottom:auto
-mb-px|margin-bottom:-1px
mb-px|margin-bottom:1px
ml-auto|margin-left:auto
-ml-px|margin-left:-1px
ml-px|margin-left:1px
box-border|box-sizing:border-box
box-content|box-sizing:content-box
block|display:block
inline-block|display:inline-block
inline|display:inline
hidden|display:none
inline-flex|display:inline-flex
table|display:table
inline-table|display:inline-table
table-caption|display:table-caption
table-cell|display:table-cell
table-column|display:table-column
table-column-group|display:table-column-group
table-footer-group|display:table-footer-group
table-header-group|display:table-header-group
table-row-group|display:table-row-group
table-row|display:table-row
flow-root|display:flow-root
flex|display:flex
grid|display:grid
inline-grid|display:inline-grid
contents|display:contents
list-item|display:list-item
field-sizing-content|field-sizing:content
field-sizing-fixed|field-sizing:fixed
size-full|--tw-sort:size;width:100%;height:100%
w-full|width:100%
h-full|height:100%
min-w-full|min-width:100%
min-h-full|min-height:100%
max-w-full|max-width:100%
max-h-full|max-height:100%
size-svw|--tw-sort:size;width:100svw;height:100svw
w-svw|width:100svw
h-svw|height:100svw
min-w-svw|min-width:100svw
min-h-svw|min-height:100svw
max-w-svw|max-width:100svw
max-h-svw|max-height:100svw
size-lvw|--tw-sort:size;width:100lvw;height:100lvw
w-lvw|width:100lvw
h-lvw|height:100lvw
min-w-lvw|min-width:100lvw
min-h-lvw|min-height:100lvw
max-w-lvw|max-width:100lvw
max-h-lvw|max-height:100lvw
size-dvw|--tw-sort:size;width:100dvw;height:100dvw
w-dvw|width:100dvw
h-dvw|height:100dvw
min-w-dvw|min-width:100dvw
min-h-dvw|min-height:100dvw
max-w-dvw|max-width:100dvw
max-h-dvw|max-height:100dvw
size-svh|--tw-sort:size;width:100svh;height:100svh
w-svh|width:100svh
h-svh|height:100svh
min-w-svh|min-width:100svh
min-h-svh|min-height:100svh
max-w-svh|max-width:100svh
max-h-svh|max-height:100svh
size-lvh|--tw-sort:size;width:100lvh;height:100lvh
w-lvh|width:100lvh
h-lvh|height:100lvh
min-w-lvh|min-width:100lvh
min-h-lvh|min-height:100lvh
max-w-lvh|max-width:100lvh
max-h-lvh|max-height:100lvh
size-dvh|--tw-sort:size;width:100dvh;height:100dvh
w-dvh|width:100dvh
h-dvh|height:100dvh
min-w-dvh|min-width:100dvh
min-h-dvh|min-height:100dvh
max-w-dvh|max-width:100dvh
max-h-dvh|max-height:100dvh
size-min|--tw-sort:size;width:min-content;height:min-content
w-min|width:min-content
h-min|height:min-content
min-w-min|min-width:min-content
min-h-min|min-height:min-content
max-w-min|max-width:min-content
max-h-min|max-height:min-content
size-max|--tw-sort:size;width:max-content;height:max-content
w-max|width:max-content
h-max|height:max-content
min-w-max|min-width:max-content
min-h-max|min-height:max-content
max-w-max|max-width:max-content
max-h-max|max-height:max-content
size-fit|--tw-sort:size;width:fit-content;height:fit-content
w-fit|width:fit-content
h-fit|height:fit-content
min-w-fit|min-width:fit-content
min-h-fit|min-height:fit-content
max-w-fit|max-width:fit-content
max-h-fit|max-height:fit-content
size-auto|--tw-sort:size;width:auto;height:auto
w-auto|width:auto
h-auto|height:auto
min-w-auto|min-width:auto
min-h-auto|min-height:auto
h-lh|height:1lh
min-h-lh|min-height:1lh
max-h-lh|max-height:1lh
w-screen|width:100vw
min-w-screen|min-width:100vw
max-w-screen|max-width:100vw
h-screen|height:100vh
min-h-screen|min-height:100vh
max-h-screen|max-height:100vh
max-w-none|max-width:none
max-h-none|max-height:none
size-px|--tw-sort:size;width:1px;height:1px
w-px|width:1px
min-w-px|min-width:1px
max-w-px|max-width:1px
h-px|height:1px
min-h-px|min-height:1px
max-h-px|max-height:1px
inline-full|inline-size:100%
block-full|block-size:100%
min-inline-full|min-inline-size:100%
min-block-full|min-block-size:100%
max-inline-full|max-inline-size:100%
max-block-full|max-block-size:100%
inline-min|inline-size:min-content
block-min|block-size:min-content
min-inline-min|min-inline-size:min-content
min-block-min|min-block-size:min-content
max-inline-min|max-inline-size:min-content
max-block-min|max-block-size:min-content
inline-max|inline-size:max-content
block-max|block-size:max-content
min-inline-max|min-inline-size:max-content
min-block-max|min-block-size:max-content
max-inline-max|max-inline-size:max-content
max-block-max|max-block-size:max-content
inline-fit|inline-size:fit-content
block-fit|block-size:fit-content
min-inline-fit|min-inline-size:fit-content
min-block-fit|min-block-size:fit-content
max-inline-fit|max-inline-size:fit-content
max-block-fit|max-block-size:fit-content
inline-svw|inline-size:100svw
min-inline-svw|min-inline-size:100svw
max-inline-svw|max-inline-size:100svw
inline-lvw|inline-size:100lvw
min-inline-lvw|min-inline-size:100lvw
max-inline-lvw|max-inline-size:100lvw
inline-dvw|inline-size:100dvw
min-inline-dvw|min-inline-size:100dvw
max-inline-dvw|max-inline-size:100dvw
block-svh|block-size:100svh
min-block-svh|min-block-size:100svh
max-block-svh|max-block-size:100svh
block-lvh|block-size:100lvh
min-block-lvh|min-block-size:100lvh
max-block-lvh|max-block-size:100lvh
block-dvh|block-size:100dvh
min-block-dvh|min-block-size:100dvh
max-block-dvh|max-block-size:100dvh
inline-auto|inline-size:auto
block-auto|block-size:auto
min-inline-auto|min-inline-size:auto
min-block-auto|min-block-size:auto
block-lh|block-size:1lh
min-block-lh|min-block-size:1lh
max-block-lh|max-block-size:1lh
inline-screen|inline-size:100vw
min-inline-screen|min-inline-size:100vw
max-inline-screen|max-inline-size:100vw
block-screen|block-size:100vh
min-block-screen|min-block-size:100vh
max-block-screen|max-block-size:100vh
max-inline-none|max-inline-size:none
max-block-none|max-block-size:none
inline-px|inline-size:1px
min-inline-px|min-inline-size:1px
max-inline-px|max-inline-size:1px
block-px|block-size:1px
min-block-px|min-block-size:1px
max-block-px|max-block-size:1px
flex-auto|flex:auto
flex-initial|flex:0 auto
flex-none|flex:none
basis-auto|flex-basis:auto
basis-full|flex-basis:100%
basis-px|flex-basis:1px
table-auto|table-layout:auto
table-fixed|table-layout:fixed
caption-top|caption-side:top
caption-bottom|caption-side:bottom
border-collapse|border-collapse:collapse
border-separate|border-collapse:separate
border-spacing-px|@--tw-border-spacing-x,0,<length>;@--tw-border-spacing-y,0,<length>;--tw-border-spacing-x:1px;--tw-border-spacing-y:1px;border-spacing:var(--tw-border-spacing-x) var(--tw-border-spacing-y)
border-spacing-x-px|@--tw-border-spacing-x,0,<length>;@--tw-border-spacing-y,0,<length>;--tw-border-spacing-x:1px;border-spacing:var(--tw-border-spacing-x) var(--tw-border-spacing-y)
border-spacing-y-px|@--tw-border-spacing-x,0,<length>;@--tw-border-spacing-y,0,<length>;--tw-border-spacing-y:1px;border-spacing:var(--tw-border-spacing-x) var(--tw-border-spacing-y)
translate-none|translate:none
-translate-full|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-x:-100%;--tw-translate-y:-100%;translate:var(--tw-translate-x) var(--tw-translate-y)
translate-full|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-x:100%;--tw-translate-y:100%;translate:var(--tw-translate-x) var(--tw-translate-y)
-translate-px|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-x:-1px;--tw-translate-y:-1px;translate:var(--tw-translate-x) var(--tw-translate-y)
translate-px|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-x:1px;--tw-translate-y:1px;translate:var(--tw-translate-x) var(--tw-translate-y)
-translate-x-full|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-x:-100%;translate:var(--tw-translate-x) var(--tw-translate-y)
translate-x-full|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-x:100%;translate:var(--tw-translate-x) var(--tw-translate-y)
-translate-x-px|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-x:-1px;translate:var(--tw-translate-x) var(--tw-translate-y)
translate-x-px|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-x:1px;translate:var(--tw-translate-x) var(--tw-translate-y)
-translate-y-full|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-y:-100%;translate:var(--tw-translate-x) var(--tw-translate-y)
translate-y-full|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-y:100%;translate:var(--tw-translate-x) var(--tw-translate-y)
-translate-y-px|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-y:-1px;translate:var(--tw-translate-x) var(--tw-translate-y)
translate-y-px|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-y:1px;translate:var(--tw-translate-x) var(--tw-translate-y)
-translate-z-px|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-z:-1px;translate:var(--tw-translate-x) var(--tw-translate-y) var(--tw-translate-z)
translate-z-px|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;--tw-translate-z:1px;translate:var(--tw-translate-x) var(--tw-translate-y) var(--tw-translate-z)
translate-3d|@--tw-translate-x,0,;@--tw-translate-y,0,;@--tw-translate-z,0,;translate:var(--tw-translate-x) var(--tw-translate-y) var(--tw-translate-z)
scale-none|scale:none
scale-3d|@--tw-scale-x,1,;@--tw-scale-y,1,;@--tw-scale-z,1,;scale:var(--tw-scale-x) var(--tw-scale-y) var(--tw-scale-z)
rotate-none|rotate:none
transform-cpu|transform:var(--tw-rotate-x,) var(--tw-rotate-y,) var(--tw-rotate-z,) var(--tw-skew-x,) var(--tw-skew-y,)
transform-gpu|transform:translateZ(0) var(--tw-rotate-x,) var(--tw-rotate-y,) var(--tw-rotate-z,) var(--tw-skew-x,) var(--tw-skew-y,)
transform-none|transform:none
transform-flat|transform-style:flat
transform-3d|transform-style:preserve-3d
transform-content|transform-box:content-box
transform-border|transform-box:border-box
transform-fill|transform-box:fill-box
transform-stroke|transform-box:stroke-box
transform-view|transform-box:view-box
backface-visible|backface-visibility:visible
backface-hidden|backface-visibility:hidden
cursor-auto|cursor:auto
cursor-default|cursor:default
cursor-pointer|cursor:pointer
cursor-wait|cursor:wait
cursor-text|cursor:text
cursor-move|cursor:move
cursor-help|cursor:help
cursor-not-allowed|cursor:not-allowed
cursor-none|cursor:none
cursor-context-menu|cursor:context-menu
cursor-progress|cursor:progress
cursor-cell|cursor:cell
cursor-crosshair|cursor:crosshair
cursor-vertical-text|cursor:vertical-text
cursor-alias|cursor:alias
cursor-copy|cursor:copy
cursor-no-drop|cursor:no-drop
cursor-grab|cursor:grab
cursor-grabbing|cursor:grabbing
cursor-all-scroll|cursor:all-scroll
cursor-col-resize|cursor:col-resize
cursor-row-resize|cursor:row-resize
cursor-n-resize|cursor:n-resize
cursor-e-resize|cursor:e-resize
cursor-s-resize|cursor:s-resize
cursor-w-resize|cursor:w-resize
cursor-ne-resize|cursor:ne-resize
cursor-nw-resize|cursor:nw-resize
cursor-se-resize|cursor:se-resize
cursor-sw-resize|cursor:sw-resize
cursor-ew-resize|cursor:ew-resize
cursor-ns-resize|cursor:ns-resize
cursor-nesw-resize|cursor:nesw-resize
cursor-nwse-resize|cursor:nwse-resize
cursor-zoom-in|cursor:zoom-in
cursor-zoom-out|cursor:zoom-out
touch-auto|touch-action:auto
touch-none|touch-action:none
touch-manipulation|touch-action:manipulation
touch-pan-x|@--tw-pan-x,,;@--tw-pan-y,,;@--tw-pinch-zoom,,;--tw-pan-x:pan-x;touch-action:var(--tw-pan-x,) var(--tw-pan-y,) var(--tw-pinch-zoom,)
touch-pan-left|@--tw-pan-x,,;@--tw-pan-y,,;@--tw-pinch-zoom,,;--tw-pan-x:pan-left;touch-action:var(--tw-pan-x,) var(--tw-pan-y,) var(--tw-pinch-zoom,)
touch-pan-right|@--tw-pan-x,,;@--tw-pan-y,,;@--tw-pinch-zoom,,;--tw-pan-x:pan-right;touch-action:var(--tw-pan-x,) var(--tw-pan-y,) var(--tw-pinch-zoom,)
touch-pan-y|@--tw-pan-x,,;@--tw-pan-y,,;@--tw-pinch-zoom,,;--tw-pan-y:pan-y;touch-action:var(--tw-pan-x,) var(--tw-pan-y,) var(--tw-pinch-zoom,)
touch-pan-up|@--tw-pan-x,,;@--tw-pan-y,,;@--tw-pinch-zoom,,;--tw-pan-y:pan-up;touch-action:var(--tw-pan-x,) var(--tw-pan-y,) var(--tw-pinch-zoom,)
touch-pan-down|@--tw-pan-x,,;@--tw-pan-y,,;@--tw-pinch-zoom,,;--tw-pan-y:pan-down;touch-action:var(--tw-pan-x,) var(--tw-pan-y,) var(--tw-pinch-zoom,)
touch-pinch-zoom|@--tw-pan-x,,;@--tw-pan-y,,;@--tw-pinch-zoom,,;--tw-pinch-zoom:pinch-zoom;touch-action:var(--tw-pan-x,) var(--tw-pan-y,) var(--tw-pinch-zoom,)
select-none|-webkit-user-select:none;user-select:none
select-text|-webkit-user-select:text;user-select:text
select-all|-webkit-user-select:all;user-select:all
select-auto|-webkit-user-select:auto;user-select:auto
resize-none|resize:none
resize-x|resize:horizontal
resize-y|resize:vertical
resize|resize:both
snap-none|scroll-snap-type:none
snap-x|@--tw-scroll-snap-strictness,proximity,;scroll-snap-type:x var(--tw-scroll-snap-strictness)
snap-y|@--tw-scroll-snap-strictness,proximity,;scroll-snap-type:y var(--tw-scroll-snap-strictness)
snap-both|@--tw-scroll-snap-strictness,proximity,;scroll-snap-type:both var(--tw-scroll-snap-strictness)
snap-mandatory|@--tw-scroll-snap-strictness,proximity,;--tw-scroll-snap-strictness:mandatory
snap-proximity|@--tw-scroll-snap-strictness,proximity,;--tw-scroll-snap-strictness:proximity
snap-align-none|scroll-snap-align:none
snap-start|scroll-snap-align:start
snap-end|scroll-snap-align:end
snap-center|scroll-snap-align:center
snap-normal|scroll-snap-stop:normal
snap-always|scroll-snap-stop:always
-scroll-m-px|scroll-margin:-1px
scroll-m-px|scroll-margin:1px
-scroll-mx-px|scroll-margin-inline:-1px
scroll-mx-px|scroll-margin-inline:1px
-scroll-my-px|scroll-margin-block:-1px
scroll-my-px|scroll-margin-block:1px
-scroll-ms-px|scroll-margin-inline-start:-1px
scroll-ms-px|scroll-margin-inline-start:1px
-scroll-me-px|scroll-margin-inline-end:-1px
scroll-me-px|scroll-margin-inline-end:1px
-scroll-mbs-px|scroll-margin-block-start:-1px
scroll-mbs-px|scroll-margin-block-start:1px
-scroll-mbe-px|scroll-margin-block-end:-1px
scroll-mbe-px|scroll-margin-block-end:1px
-scroll-mt-px|scroll-margin-top:-1px
scroll-mt-px|scroll-margin-top:1px
-scroll-mr-px|scroll-margin-right:-1px
scroll-mr-px|scroll-margin-right:1px
-scroll-mb-px|scroll-margin-bottom:-1px
scroll-mb-px|scroll-margin-bottom:1px
-scroll-ml-px|scroll-margin-left:-1px
scroll-ml-px|scroll-margin-left:1px
scroll-p-px|scroll-padding:1px
scroll-px-px|scroll-padding-inline:1px
scroll-py-px|scroll-padding-block:1px
scroll-ps-px|scroll-padding-inline-start:1px
scroll-pe-px|scroll-padding-inline-end:1px
scroll-pbs-px|scroll-padding-block-start:1px
scroll-pbe-px|scroll-padding-block-end:1px
scroll-pt-px|scroll-padding-top:1px
scroll-pr-px|scroll-padding-right:1px
scroll-pb-px|scroll-padding-bottom:1px
scroll-pl-px|scroll-padding-left:1px
list-inside|list-style-position:inside
list-outside|list-style-position:outside
appearance-none|appearance:none
appearance-auto|appearance:auto
scheme-normal|color-scheme:normal
scheme-dark|color-scheme:dark
scheme-light|color-scheme:light
scheme-light-dark|color-scheme:light dark
scheme-only-dark|color-scheme:only dark
scheme-only-light|color-scheme:only light
break-before-auto|break-before:auto
break-before-avoid|break-before:avoid
break-before-all|break-before:all
break-before-avoid-page|break-before:avoid-page
break-before-page|break-before:page
break-before-left|break-before:left
break-before-right|break-before:right
break-before-column|break-before:column
break-inside-auto|break-inside:auto
break-inside-avoid|break-inside:avoid
break-inside-avoid-page|break-inside:avoid-page
break-inside-avoid-column|break-inside:avoid-column
break-after-auto|break-after:auto
break-after-avoid|break-after:avoid
break-after-all|break-after:all
break-after-avoid-page|break-after:avoid-page
break-after-page|break-after:page
break-after-left|break-after:left
break-after-right|break-after:right
break-after-column|break-after:column
grid-flow-row|grid-auto-flow:row
grid-flow-col|grid-auto-flow:column
grid-flow-dense|grid-auto-flow:dense
grid-flow-row-dense|grid-auto-flow:row dense
grid-flow-col-dense|grid-auto-flow:column dense
flex-row|flex-direction:row
flex-row-reverse|flex-direction:row-reverse
flex-col|flex-direction:column
flex-col-reverse|flex-direction:column-reverse
flex-wrap|flex-wrap:wrap
flex-nowrap|flex-wrap:nowrap
flex-wrap-reverse|flex-wrap:wrap-reverse
place-content-center|place-content:center
place-content-start|place-content:start
place-content-end|place-content:end
place-content-center-safe|place-content:safe center
place-content-end-safe|place-content:safe end
place-content-between|place-content:space-between
place-content-around|place-content:space-around
place-content-evenly|place-content:space-evenly
place-content-baseline|place-content:baseline
place-content-stretch|place-content:stretch
place-items-center|place-items:center
place-items-start|place-items:start
place-items-end|place-items:end
place-items-center-safe|place-items:safe center
place-items-end-safe|place-items:safe end
place-items-baseline|place-items:baseline
place-items-stretch|place-items:stretch
content-normal|align-content:normal
content-center|align-content:center
content-start|align-content:flex-start
content-end|align-content:flex-end
content-center-safe|align-content:safe center
content-end-safe|align-content:safe flex-end
content-between|align-content:space-between
content-around|align-content:space-around
content-evenly|align-content:space-evenly
content-baseline|align-content:baseline
content-stretch|align-content:stretch
items-center|align-items:center
items-start|align-items:flex-start
items-end|align-items:flex-end
items-center-safe|align-items:safe center
items-end-safe|align-items:safe flex-end
items-baseline|align-items:baseline
items-baseline-last|align-items:last baseline
items-stretch|align-items:stretch
justify-normal|justify-content:normal
justify-center|justify-content:center
justify-start|justify-content:flex-start
justify-end|justify-content:flex-end
justify-center-safe|justify-content:safe center
justify-end-safe|justify-content:safe flex-end
justify-between|justify-content:space-between
justify-around|justify-content:space-around
justify-evenly|justify-content:space-evenly
justify-baseline|justify-content:baseline
justify-stretch|justify-content:stretch
justify-items-normal|justify-items:normal
justify-items-center|justify-items:center
justify-items-start|justify-items:start
justify-items-end|justify-items:end
justify-items-center-safe|justify-items:safe center
justify-items-end-safe|justify-items:safe end
justify-items-stretch|justify-items:stretch
gap-px|gap:1px
gap-x-px|column-gap:1px
gap-y-px|row-gap:1px
-space-x-px|@--tw-space-x-reverse,0,;&:where(& > :not(:last-child)){--tw-sort:row-gap;--tw-space-x-reverse:0;margin-inline-start:calc(-1px * var(--tw-space-x-reverse));margin-inline-end:calc(-1px * calc(1 - var(--tw-space-x-reverse)))}
space-x-px|@--tw-space-x-reverse,0,;&:where(& > :not(:last-child)){--tw-sort:row-gap;--tw-space-x-reverse:0;margin-inline-start:calc(1px * var(--tw-space-x-reverse));margin-inline-end:calc(1px * calc(1 - var(--tw-space-x-reverse)))}
-space-y-px|@--tw-space-y-reverse,0,;&:where(& > :not(:last-child)){--tw-sort:column-gap;--tw-space-y-reverse:0;margin-block-start:calc(-1px * var(--tw-space-y-reverse));margin-block-end:calc(-1px * calc(1 - var(--tw-space-y-reverse)))}
space-y-px|@--tw-space-y-reverse,0,;&:where(& > :not(:last-child)){--tw-sort:column-gap;--tw-space-y-reverse:0;margin-block-start:calc(1px * var(--tw-space-y-reverse));margin-block-end:calc(1px * calc(1 - var(--tw-space-y-reverse)))}
space-x-reverse|@--tw-space-x-reverse,0,;&:where(& > :not(:last-child)){--tw-sort:row-gap;--tw-space-x-reverse:1}
space-y-reverse|@--tw-space-y-reverse,0,;&:where(& > :not(:last-child)){--tw-sort:column-gap;--tw-space-y-reverse:1}
accent-auto|accent-color:auto
place-self-auto|place-self:auto
place-self-start|place-self:start
place-self-end|place-self:end
place-self-center|place-self:center
place-self-end-safe|place-self:safe end
place-self-center-safe|place-self:safe center
place-self-stretch|place-self:stretch
self-auto|align-self:auto
self-start|align-self:flex-start
self-end|align-self:flex-end
self-center|align-self:center
self-end-safe|align-self:safe flex-end
self-center-safe|align-self:safe center
self-stretch|align-self:stretch
self-baseline|align-self:baseline
self-baseline-last|align-self:last baseline
justify-self-auto|justify-self:auto
justify-self-start|justify-self:flex-start
justify-self-end|justify-self:flex-end
justify-self-center|justify-self:center
justify-self-end-safe|justify-self:safe flex-end
justify-self-center-safe|justify-self:safe center
justify-self-stretch|justify-self:stretch
overflow-auto|overflow:auto
overflow-x-auto|overflow-x:auto
overflow-y-auto|overflow-y:auto
overflow-hidden|overflow:hidden
overflow-x-hidden|overflow-x:hidden
overflow-y-hidden|overflow-y:hidden
overflow-clip|overflow:clip
overflow-x-clip|overflow-x:clip
overflow-y-clip|overflow-y:clip
overflow-visible|overflow:visible
overflow-x-visible|overflow-x:visible
overflow-y-visible|overflow-y:visible
overflow-scroll|overflow:scroll
overflow-x-scroll|overflow-x:scroll
overflow-y-scroll|overflow-y:scroll
overscroll-auto|overscroll-behavior:auto
overscroll-x-auto|overscroll-behavior-x:auto
overscroll-y-auto|overscroll-behavior-y:auto
overscroll-contain|overscroll-behavior:contain
overscroll-x-contain|overscroll-behavior-x:contain
overscroll-y-contain|overscroll-behavior-y:contain
overscroll-none|overscroll-behavior:none
overscroll-x-none|overscroll-behavior-x:none
overscroll-y-none|overscroll-behavior-y:none
scroll-auto|scroll-behavior:auto
scroll-smooth|scroll-behavior:smooth
scrollbar-auto|scrollbar-width:auto
scrollbar-thin|scrollbar-width:thin
scrollbar-none|scrollbar-width:none
scrollbar-gutter-auto|scrollbar-gutter:auto
scrollbar-gutter-stable|scrollbar-gutter:stable
scrollbar-gutter-both|scrollbar-gutter:stable both-edges
truncate|overflow:hidden;text-overflow:ellipsis;white-space:nowrap
text-ellipsis|text-overflow:ellipsis
text-clip|text-overflow:clip
hyphens-none|-webkit-hyphens:none;hyphens:none
hyphens-manual|-webkit-hyphens:manual;hyphens:manual
hyphens-auto|-webkit-hyphens:auto;hyphens:auto
whitespace-normal|white-space:normal
whitespace-nowrap|white-space:nowrap
whitespace-pre|white-space:pre
whitespace-pre-line|white-space:pre-line
whitespace-pre-wrap|white-space:pre-wrap
whitespace-break-spaces|white-space:break-spaces
text-wrap|text-wrap:wrap
text-nowrap|text-wrap:nowrap
text-balance|text-wrap:balance
text-pretty|text-wrap:pretty
break-normal|overflow-wrap:normal;word-break:normal
break-all|word-break:break-all
break-keep|word-break:keep-all
wrap-anywhere|overflow-wrap:anywhere
wrap-break-word|overflow-wrap:break-word
wrap-normal|overflow-wrap:normal
border-solid|--tw-border-style:solid;border-style:solid
border-dashed|--tw-border-style:dashed;border-style:dashed
border-dotted|--tw-border-style:dotted;border-style:dotted
border-double|--tw-border-style:double;border-style:double
border-hidden|--tw-border-style:hidden;border-style:hidden
border-none|--tw-border-style:none;border-style:none
divide-x-reverse|@--tw-divide-x-reverse,0,;&:where(& > :not(:last-child)){--tw-divide-x-reverse:1}
divide-y-reverse|@--tw-divide-y-reverse,0,;&:where(& > :not(:last-child)){--tw-divide-y-reverse:1}
divide-solid|&:where(& > :not(:last-child)){--tw-sort:divide-style;--tw-border-style:solid;border-style:solid}
divide-dashed|&:where(& > :not(:last-child)){--tw-sort:divide-style;--tw-border-style:dashed;border-style:dashed}
divide-dotted|&:where(& > :not(:last-child)){--tw-sort:divide-style;--tw-border-style:dotted;border-style:dotted}
divide-double|&:where(& > :not(:last-child)){--tw-sort:divide-style;--tw-border-style:double;border-style:double}
divide-none|&:where(& > :not(:last-child)){--tw-sort:divide-style;--tw-border-style:none;border-style:none}
bg-auto|background-size:auto
bg-cover|background-size:cover
bg-contain|background-size:contain
bg-fixed|background-attachment:fixed
bg-local|background-attachment:local
bg-scroll|background-attachment:scroll
bg-top|background-position:top
bg-top-left|background-position:left top
bg-top-right|background-position:right top
bg-bottom|background-position:bottom
bg-bottom-left|background-position:left bottom
bg-bottom-right|background-position:right bottom
bg-left|background-position:left
bg-right|background-position:right
bg-center|background-position:center
bg-repeat|background-repeat:repeat
bg-no-repeat|background-repeat:no-repeat
bg-repeat-x|background-repeat:repeat-x
bg-repeat-y|background-repeat:repeat-y
bg-repeat-round|background-repeat:round
bg-repeat-space|background-repeat:space
bg-none|background-image:none
via-none|--tw-gradient-via-stops:initial
mask-none|mask-image:none
mask-add|mask-composite:add
mask-subtract|mask-composite:subtract
mask-intersect|mask-composite:intersect
mask-exclude|mask-composite:exclude
mask-alpha|mask-mode:alpha
mask-luminance|mask-mode:luminance
mask-match|mask-mode:match-source
mask-type-alpha|mask-type:alpha
mask-type-luminance|mask-type:luminance
mask-auto|mask-size:auto
mask-cover|mask-size:cover
mask-contain|mask-size:contain
mask-top|mask-position:top
mask-top-left|mask-position:left top
mask-top-right|mask-position:right top
mask-bottom|mask-position:bottom
mask-bottom-left|mask-position:left bottom
mask-bottom-right|mask-position:right bottom
mask-left|mask-position:left
mask-right|mask-position:right
mask-center|mask-position:center
mask-repeat|mask-repeat:repeat
mask-no-repeat|mask-repeat:no-repeat
mask-repeat-x|mask-repeat:repeat-x
mask-repeat-y|mask-repeat:repeat-y
mask-repeat-round|mask-repeat:round
mask-repeat-space|mask-repeat:space
mask-clip-border|mask-clip:border-box
mask-clip-padding|mask-clip:padding-box
mask-clip-content|mask-clip:content-box
mask-clip-fill|mask-clip:fill-box
mask-clip-stroke|mask-clip:stroke-box
mask-clip-view|mask-clip:view-box
mask-no-clip|mask-clip:no-clip
mask-origin-border|mask-origin:border-box
mask-origin-padding|mask-origin:padding-box
mask-origin-content|mask-origin:content-box
mask-origin-fill|mask-origin:fill-box
mask-origin-stroke|mask-origin:stroke-box
mask-origin-view|mask-origin:view-box
mask-circle|--tw-mask-radial-shape:circle
mask-ellipse|--tw-mask-radial-shape:ellipse
mask-radial-closest-side|--tw-mask-radial-size:closest-side
mask-radial-farthest-side|--tw-mask-radial-size:farthest-side
mask-radial-closest-corner|--tw-mask-radial-size:closest-corner
mask-radial-farthest-corner|--tw-mask-radial-size:farthest-corner
mask-radial-at-top|--tw-mask-radial-position:top
mask-radial-at-top-left|--tw-mask-radial-position:top left
mask-radial-at-top-right|--tw-mask-radial-position:top right
mask-radial-at-bottom|--tw-mask-radial-position:bottom
mask-radial-at-bottom-left|--tw-mask-radial-position:bottom left
mask-radial-at-bottom-right|--tw-mask-radial-position:bottom right
mask-radial-at-left|--tw-mask-radial-position:left
mask-radial-at-right|--tw-mask-radial-position:right
mask-radial-at-center|--tw-mask-radial-position:center
box-decoration-slice|-webkit-box-decoration-break:slice;box-decoration-break:slice
box-decoration-clone|-webkit-box-decoration-break:clone;box-decoration-break:clone
bg-clip-text|background-clip:text
bg-clip-border|background-clip:border-box
bg-clip-padding|background-clip:padding-box
bg-clip-content|background-clip:content-box
bg-origin-border|background-origin:border-box
bg-origin-padding|background-origin:padding-box
bg-origin-content|background-origin:content-box
bg-blend-normal|background-blend-mode:normal
mix-blend-normal|mix-blend-mode:normal
bg-blend-multiply|background-blend-mode:multiply
mix-blend-multiply|mix-blend-mode:multiply
bg-blend-screen|background-blend-mode:screen
mix-blend-screen|mix-blend-mode:screen
bg-blend-overlay|background-blend-mode:overlay
mix-blend-overlay|mix-blend-mode:overlay
bg-blend-darken|background-blend-mode:darken
mix-blend-darken|mix-blend-mode:darken
bg-blend-lighten|background-blend-mode:lighten
mix-blend-lighten|mix-blend-mode:lighten
bg-blend-color-dodge|background-blend-mode:color-dodge
mix-blend-color-dodge|mix-blend-mode:color-dodge
bg-blend-color-burn|background-blend-mode:color-burn
mix-blend-color-burn|mix-blend-mode:color-burn
bg-blend-hard-light|background-blend-mode:hard-light
mix-blend-hard-light|mix-blend-mode:hard-light
bg-blend-soft-light|background-blend-mode:soft-light
mix-blend-soft-light|mix-blend-mode:soft-light
bg-blend-difference|background-blend-mode:difference
mix-blend-difference|mix-blend-mode:difference
bg-blend-exclusion|background-blend-mode:exclusion
mix-blend-exclusion|mix-blend-mode:exclusion
bg-blend-hue|background-blend-mode:hue
mix-blend-hue|mix-blend-mode:hue
bg-blend-saturation|background-blend-mode:saturation
mix-blend-saturation|mix-blend-mode:saturation
bg-blend-color|background-blend-mode:color
mix-blend-color|mix-blend-mode:color
bg-blend-luminosity|background-blend-mode:luminosity
mix-blend-luminosity|mix-blend-mode:luminosity
mix-blend-plus-darker|mix-blend-mode:plus-darker
mix-blend-plus-lighter|mix-blend-mode:plus-lighter
fill-none|fill:none
stroke-none|stroke:none
object-contain|object-fit:contain
object-cover|object-fit:cover
object-fill|object-fit:fill
object-none|object-fit:none
object-scale-down|object-fit:scale-down
p-px|padding:1px
px-px|padding-inline:1px
py-px|padding-block:1px
ps-px|padding-inline-start:1px
pe-px|padding-inline-end:1px
pbs-px|padding-block-start:1px
pbe-px|padding-block-end:1px
pt-px|padding-top:1px
pr-px|padding-right:1px
pb-px|padding-bottom:1px
pl-px|padding-left:1px
text-left|text-align:left
text-center|text-align:center
text-right|text-align:right
text-justify|text-align:justify
text-start|text-align:start
text-end|text-align:end
-indent-px|text-indent:-1px
indent-px|text-indent:1px
align-baseline|vertical-align:baseline
align-top|vertical-align:top
align-middle|vertical-align:middle
align-bottom|vertical-align:bottom
align-text-top|vertical-align:text-top
align-text-bottom|vertical-align:text-bottom
align-sub|vertical-align:sub
align-super|vertical-align:super
uppercase|text-transform:uppercase
lowercase|text-transform:lowercase
capitalize|text-transform:capitalize
normal-case|text-transform:none
italic|font-style:italic
not-italic|font-style:normal
underline|text-decoration-line:underline
overline|text-decoration-line:overline
line-through|text-decoration-line:line-through
no-underline|text-decoration-line:none
font-stretch-normal|font-stretch:normal
font-stretch-ultra-condensed|font-stretch:ultra-condensed
font-stretch-extra-condensed|font-stretch:extra-condensed
font-stretch-condensed|font-stretch:condensed
font-stretch-semi-condensed|font-stretch:semi-condensed
font-stretch-semi-expanded|font-stretch:semi-expanded
font-stretch-expanded|font-stretch:expanded
font-stretch-extra-expanded|font-stretch:extra-expanded
font-stretch-ultra-expanded|font-stretch:ultra-expanded
decoration-solid|text-decoration-style:solid
decoration-double|text-decoration-style:double
decoration-dotted|text-decoration-style:dotted
decoration-dashed|text-decoration-style:dashed
decoration-wavy|text-decoration-style:wavy
decoration-auto|text-decoration-thickness:auto
decoration-from-font|text-decoration-thickness:from-font
drop-shadow-none|@--tw-blur,,;@--tw-brightness,,;@--tw-contrast,,;@--tw-grayscale,,;@--tw-hue-rotate,,;@--tw-invert,,;@--tw-opacity,,;@--tw-saturate,,;@--tw-sepia,,;@--tw-drop-shadow,,;@--tw-drop-shadow-color,,;@--tw-drop-shadow-alpha,100%,<percentage>;@--tw-drop-shadow-size,,;--tw-drop-shadow: ;filter:var(--tw-blur,) var(--tw-brightness,) var(--tw-contrast,) var(--tw-grayscale,) var(--tw-hue-rotate,) var(--tw-invert,) var(--tw-saturate,) var(--tw-sepia,) var(--tw-drop-shadow,)
transition-discrete|transition-behavior:allow-discrete
transition-normal|transition-behavior:normal
duration-initial|@--tw-duration,,;--tw-duration:initial
will-change-auto|will-change:auto
will-change-scroll|will-change:scroll-position
will-change-contents|will-change:contents
will-change-transform|will-change:transform
content-none|--tw-content:none;content:none
contain-none|contain:none
contain-content|contain:content
contain-strict|contain:strict
contain-size|@--tw-contain-size,,;@--tw-contain-layout,,;@--tw-contain-paint,,;@--tw-contain-style,,;--tw-contain-size:size;contain:var(--tw-contain-size,) var(--tw-contain-layout,) var(--tw-contain-paint,) var(--tw-contain-style,)
contain-inline-size|@--tw-contain-size,,;@--tw-contain-layout,,;@--tw-contain-paint,,;@--tw-contain-style,,;--tw-contain-size:inline-size;contain:var(--tw-contain-size,) var(--tw-contain-layout,) var(--tw-contain-paint,) var(--tw-contain-style,)
contain-layout|@--tw-contain-size,,;@--tw-contain-layout,,;@--tw-contain-paint,,;@--tw-contain-style,,;--tw-contain-layout:layout;contain:var(--tw-contain-size,) var(--tw-contain-layout,) var(--tw-contain-paint,) var(--tw-contain-style,)
contain-paint|@--tw-contain-size,,;@--tw-contain-layout,,;@--tw-contain-paint,,;@--tw-contain-style,,;--tw-contain-paint:paint;contain:var(--tw-contain-size,) var(--tw-contain-layout,) var(--tw-contain-paint,) var(--tw-contain-style,)
contain-style|@--tw-contain-size,,;@--tw-contain-layout,,;@--tw-contain-paint,,;@--tw-contain-style,,;--tw-contain-style:style;contain:var(--tw-contain-size,) var(--tw-contain-layout,) var(--tw-contain-paint,) var(--tw-contain-style,)
forced-color-adjust-none|forced-color-adjust:none
forced-color-adjust-auto|forced-color-adjust:auto
leading-px|@--tw-leading,,;--tw-leading:1px;line-height:1px
antialiased|-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale
subpixel-antialiased|-webkit-font-smoothing:auto;-moz-osx-font-smoothing:auto
normal-nums|font-variant-numeric:normal
ordinal|@--tw-ordinal,,;@--tw-slashed-zero,,;@--tw-numeric-figure,,;@--tw-numeric-spacing,,;@--tw-numeric-fraction,,;--tw-ordinal:ordinal;font-variant-numeric:var(--tw-ordinal,) var(--tw-slashed-zero,) var(--tw-numeric-figure,) var(--tw-numeric-spacing,) var(--tw-numeric-fraction,)
slashed-zero|@--tw-ordinal,,;@--tw-slashed-zero,,;@--tw-numeric-figure,,;@--tw-numeric-spacing,,;@--tw-numeric-fraction,,;--tw-slashed-zero:slashed-zero;font-variant-numeric:var(--tw-ordinal,) var(--tw-slashed-zero,) var(--tw-numeric-figure,) var(--tw-numeric-spacing,) var(--tw-numeric-fraction,)
lining-nums|@--tw-ordinal,,;@--tw-slashed-zero,,;@--tw-numeric-figure,,;@--tw-numeric-spacing,,;@--tw-numeric-fraction,,;--tw-numeric-figure:lining-nums;font-variant-numeric:var(--tw-ordinal,) var(--tw-slashed-zero,) var(--tw-numeric-figure,) var(--tw-numeric-spacing,) var(--tw-numeric-fraction,)
oldstyle-nums|@--tw-ordinal,,;@--tw-slashed-zero,,;@--tw-numeric-figure,,;@--tw-numeric-spacing,,;@--tw-numeric-fraction,,;--tw-numeric-figure:oldstyle-nums;font-variant-numeric:var(--tw-ordinal,) var(--tw-slashed-zero,) var(--tw-numeric-figure,) var(--tw-numeric-spacing,) var(--tw-numeric-fraction,)
proportional-nums|@--tw-ordinal,,;@--tw-slashed-zero,,;@--tw-numeric-figure,,;@--tw-numeric-spacing,,;@--tw-numeric-fraction,,;--tw-numeric-spacing:proportional-nums;font-variant-numeric:var(--tw-ordinal,) var(--tw-slashed-zero,) var(--tw-numeric-figure,) var(--tw-numeric-spacing,) var(--tw-numeric-fraction,)
tabular-nums|@--tw-ordinal,,;@--tw-slashed-zero,,;@--tw-numeric-figure,,;@--tw-numeric-spacing,,;@--tw-numeric-fraction,,;--tw-numeric-spacing:tabular-nums;font-variant-numeric:var(--tw-ordinal,) var(--tw-slashed-zero,) var(--tw-numeric-figure,) var(--tw-numeric-spacing,) var(--tw-numeric-fraction,)
diagonal-fractions|@--tw-ordinal,,;@--tw-slashed-zero,,;@--tw-numeric-figure,,;@--tw-numeric-spacing,,;@--tw-numeric-fraction,,;--tw-numeric-fraction:diagonal-fractions;font-variant-numeric:var(--tw-ordinal,) var(--tw-slashed-zero,) var(--tw-numeric-figure,) var(--tw-numeric-spacing,) var(--tw-numeric-fraction,)
stacked-fractions|@--tw-ordinal,,;@--tw-slashed-zero,,;@--tw-numeric-figure,,;@--tw-numeric-spacing,,;@--tw-numeric-fraction,,;--tw-numeric-fraction:stacked-fractions;font-variant-numeric:var(--tw-ordinal,) var(--tw-slashed-zero,) var(--tw-numeric-figure,) var(--tw-numeric-spacing,) var(--tw-numeric-fraction,)
outline-none|--tw-outline-style:none;outline-style:none
outline-solid|--tw-outline-style:solid;outline-style:solid
outline-dashed|--tw-outline-style:dashed;outline-style:dashed
outline-dotted|--tw-outline-style:dotted;outline-style:dotted
outline-double|--tw-outline-style:double;outline-style:double
text-shadow-initial|@--tw-text-shadow-color,,;@--tw-text-shadow-alpha,100%,<percentage>;--tw-text-shadow-color:initial
shadow-initial|@--tw-shadow,0 0 #0000,;@--tw-shadow-color,,;@--tw-shadow-alpha,100%,<percentage>;@--tw-inset-shadow,0 0 #0000,;@--tw-inset-shadow-color,,;@--tw-inset-shadow-alpha,100%,<percentage>;@--tw-ring-color,,;@--tw-ring-shadow,0 0 #0000,;@--tw-inset-ring-color,,;@--tw-inset-ring-shadow,0 0 #0000,;@--tw-ring-inset,,;@--tw-ring-offset-width,0px,<length>;@--tw-ring-offset-color,#fff,;@--tw-ring-offset-shadow,0 0 #0000,;--tw-shadow-color:initial
inset-shadow-initial|@--tw-shadow,0 0 #0000,;@--tw-shadow-color,,;@--tw-shadow-alpha,100%,<percentage>;@--tw-inset-shadow,0 0 #0000,;@--tw-inset-shadow-color,,;@--tw-inset-shadow-alpha,100%,<percentage>;@--tw-ring-color,,;@--tw-ring-shadow,0 0 #0000,;@--tw-inset-ring-color,,;@--tw-inset-ring-shadow,0 0 #0000,;@--tw-ring-inset,,;@--tw-ring-offset-width,0px,<length>;@--tw-ring-offset-color,#fff,;@--tw-ring-offset-shadow,0 0 #0000,;--tw-inset-shadow-color:initial
ring-inset|@--tw-shadow,0 0 #0000,;@--tw-shadow-color,,;@--tw-shadow-alpha,100%,<percentage>;@--tw-inset-shadow,0 0 #0000,;@--tw-inset-shadow-color,,;@--tw-inset-shadow-alpha,100%,<percentage>;@--tw-ring-color,,;@--tw-ring-shadow,0 0 #0000,;@--tw-inset-ring-color,,;@--tw-inset-ring-shadow,0 0 #0000,;@--tw-ring-inset,,;@--tw-ring-offset-width,0px,<length>;@--tw-ring-offset-color,#fff,;@--tw-ring-offset-shadow,0 0 #0000,;--tw-ring-inset:inset
bg-gradient-to-t|--tw-gradient-position:to top in oklab;background-image:linear-gradient(var(--tw-gradient-stops))
bg-gradient-to-tr|--tw-gradient-position:to top right in oklab;background-image:linear-gradient(var(--tw-gradient-stops))
bg-gradient-to-r|--tw-gradient-position:to right in oklab;background-image:linear-gradient(var(--tw-gradient-stops))
bg-gradient-to-br|--tw-gradient-position:to bottom right in oklab;background-image:linear-gradient(var(--tw-gradient-stops))
bg-gradient-to-b|--tw-gradient-position:to bottom in oklab;background-image:linear-gradient(var(--tw-gradient-stops))
bg-gradient-to-bl|--tw-gradient-position:to bottom left in oklab;background-image:linear-gradient(var(--tw-gradient-stops))
bg-gradient-to-l|--tw-gradient-position:to left in oklab;background-image:linear-gradient(var(--tw-gradient-stops))
bg-gradient-to-tl|--tw-gradient-position:to top left in oklab;background-image:linear-gradient(var(--tw-gradient-stops))
bg-left-top|background-position:left top
bg-right-top|background-position:right top
bg-left-bottom|background-position:left bottom
bg-right-bottom|background-position:right bottom
object-left-top|object-position:left top
object-right-top|object-position:right top
object-left-bottom|object-position:left bottom
object-right-bottom|object-position:right bottom
overflow-ellipsis|text-overflow:ellipsis
decoration-slice|-webkit-box-decoration-break:slice;box-decoration-break:slice
decoration-clone|-webkit-box-decoration-break:clone;box-decoration-break:clone
order-none|order:0
break-words|overflow-wrap:break-word
start-auto|inset-inline-start:auto
start-full|inset-inline-start:100%
-start-full|inset-inline-start:-100%
start-px|inset-inline-start:1px
-start-px|inset-inline-start:-1px
end-auto|inset-inline-end:auto
end-full|inset-inline-end:100%
-end-full|inset-inline-end:-100%
end-px|inset-inline-end:1px
-end-px|inset-inline-end:-1px`

// variantTable lists the static variants:
// name|order|branches|declarations|properties. Branches are separated by
// tabs; each is rules (R selector) and at-rules (A prelude) nested in each
// other, separated by " => ". Declarations are separated by ; and @property
// rules by tabs. The order of the breakpoint variants, which come from the
// theme, is @breakpoint's.
const variantTable = `*|1|R :is(& > *)||
**|2|R :is(& *)||
first-letter|6|R &::first-letter||
first-line|7|R &::first-line||
marker|8|R & *::marker	R &::marker	R & *::-webkit-details-marker	R &::-webkit-details-marker||
selection|9|R & *::selection	R &::selection||
file|10|R &::file-selector-button||
placeholder|11|R &::placeholder||
backdrop|12|R &::backdrop||
details-content|13|R &::details-content||
before|14|R &::before|content:var(--tw-content)|@property --tw-content {syntax: "*"; initial-value: ""; inherits: false;}
after|15|R &::after|content:var(--tw-content)|@property --tw-content {syntax: "*"; initial-value: ""; inherits: false;}
first|16|R &:first-child||
last|17|R &:last-child||
only|18|R &:only-child||
odd|19|R &:nth-child(odd)||
even|20|R &:nth-child(even)||
first-of-type|21|R &:first-of-type||
last-of-type|22|R &:last-of-type||
only-of-type|23|R &:only-of-type||
visited|24|R &:visited||
target|25|R &:target||
open|26|R &:is([open], :popover-open, :open)||
default|27|R &:default||
checked|28|R &:checked||
indeterminate|29|R &:indeterminate||
placeholder-shown|30|R &:placeholder-shown||
autofill|31|R &:autofill||
optional|32|R &:optional||
required|33|R &:required||
valid|34|R &:valid||
invalid|35|R &:invalid||
user-valid|36|R &:user-valid||
user-invalid|37|R &:user-invalid||
in-range|38|R &:in-range||
out-of-range|39|R &:out-of-range||
read-only|40|R &:read-only||
empty|41|R &:empty||
focus-within|42|R &:focus-within||
hover|43|R &:hover => A @media (hover: hover)||
focus|44|R &:focus||
focus-visible|45|R &:focus-visible||
active|46|R &:active||
enabled|47|R &:enabled||
disabled|48|R &:disabled||
inert|49|R &:is([inert], [inert] *)||
motion-safe|59|A @media (prefers-reduced-motion: no-preference)||
motion-reduce|60|A @media (prefers-reduced-motion: reduce)||
contrast-more|61|A @media (prefers-contrast: more)||
contrast-less|62|A @media (prefers-contrast: less)||
portrait|67|A @media (orientation: portrait)||
landscape|68|A @media (orientation: landscape)||
ltr|69|R &:where(:dir(ltr), [dir="ltr"], [dir="ltr"] *)||
rtl|70|R &:where(:dir(rtl), [dir="rtl"], [dir="rtl"] *)||
dark|71|A @media (prefers-color-scheme: dark)||
starting|72|A @starting-style||
print|73|A @media print||
forced-colors|74|A @media (forced-colors: active)||
inverted-colors|75|A @media (inverted-colors: inverted)||
pointer-none|76|A @media (pointer: none)||
pointer-coarse|77|A @media (pointer: coarse)||
pointer-fine|78|A @media (pointer: fine)||
any-pointer-none|79|A @media (any-pointer: none)||
any-pointer-coarse|80|A @media (any-pointer: coarse)||
any-pointer-fine|81|A @media (any-pointer: fine)||
noscript|82|A @media (scripting: none)||
@breakpoint|64`

// propertyOrder sorts utilities by the properties they set.
const propertyOrder = `container-type
pointer-events
visibility
position
inset
inset-inline
inset-block
inset-inline-start
inset-inline-end
inset-block-start
inset-block-end
top
right
bottom
left
isolation
z-index
order
grid-column
grid-column-start
grid-column-end
grid-row
grid-row-start
grid-row-end
float
clear
--tw-container-component
margin
margin-inline
margin-block
margin-inline-start
margin-inline-end
margin-block-start
margin-block-end
margin-top
margin-right
margin-bottom
margin-left
box-sizing
display
field-sizing
aspect-ratio
height
max-height
min-height
width
max-width
min-width
flex
flex-shrink
flex-grow
flex-basis
table-layout
caption-side
border-collapse
border-spacing
transform-origin
translate
--tw-translate-x
--tw-translate-y
--tw-translate-z
scale
--tw-scale-x
--tw-scale-y
--tw-scale-z
rotate
--tw-rotate-x
--tw-rotate-y
--tw-rotate-z
--tw-skew-x
--tw-skew-y
transform
zoom
animation
cursor
touch-action
--tw-pan-x
--tw-pan-y
--tw-pinch-zoom
resize
scroll-snap-type
--tw-scroll-snap-strictness
scroll-snap-align
scroll-snap-stop
scroll-margin
scroll-margin-inline
scroll-margin-block
scroll-margin-inline-start
scroll-margin-inline-end
scroll-margin-block-start
scroll-margin-block-end
scroll-margin-top
scroll-margin-right
scroll-margin-bottom
scroll-margin-left
scroll-padding
scroll-padding-inline
scroll-padding-block
scroll-padding-inline-start
scroll-padding-inline-end
scroll-padding-block-start
scroll-padding-block-end
scroll-padding-top
scroll-padding-right
scroll-padding-bottom
scroll-padding-left
scrollbar-width
scrollbar-color
scrollbar-gutter
list-style-position
list-style-type
list-style-image
appearance
columns
break-before
break-inside
break-after
grid-auto-columns
grid-auto-flow
grid-auto-rows
grid-template-columns
grid-template-rows
flex-direction
flex-wrap
place-content
place-items
align-content
align-items
justify-content
justify-items
gap
column-gap
row-gap
--tw-space-x-reverse
--tw-space-y-reverse
divide-x-width
divide-y-width
--tw-divide-y-reverse
divide-style
divide-color
place-self
align-self
justify-self
overflow
overflow-x
overflow-y
overscroll-behavior
overscroll-behavior-x
overscroll-behavior-y
scroll-behavior
border-radius
border-start-radius
border-end-radius
border-top-radius
border-right-radius
border-bottom-radius
border-left-radius
border-start-start-radius
border-start-end-radius
border-end-end-radius
border-end-start-radius
border-top-left-radius
border-top-right-radius
border-bottom-right-radius
border-bottom-left-radius
border-width
border-inline-width
border-block-width
border-inline-start-width
border-inline-end-width
border-block-start-width
border-block-end-width
border-top-width
border-right-width
border-bottom-width
border-left-width
border-style
border-inline-style
border-block-style
border-inline-start-style
border-inline-end-style
border-block-start-style
border-block-end-style
border-top-style
border-right-style
border-bottom-style
border-left-style
border-color
border-inline-color
border-block-color
border-inline-start-color
border-inline-end-color
border-block-start-color
border-block-end-color
border-top-color
border-right-color
border-bottom-color
border-left-color
background-color
background-image
--tw-gradient-position
--tw-gradient-stops
--tw-gradient-via-stops
--tw-gradient-from
--tw-gradient-from-position
--tw-gradient-via
--tw-gradient-via-position
--tw-gradient-to
--tw-gradient-to-position
mask-image
--tw-mask-top
--tw-mask-top-from-color
--tw-mask-top-from-position
--tw-mask-top-to-color
--tw-mask-top-to-position
--tw-mask-right
--tw-mask-right-from-color
--tw-mask-right-from-position
--tw-mask-right-to-color
--tw-mask-right-to-position
--tw-mask-bottom
--tw-mask-bottom-from-color
--tw-mask-bottom-from-position
--tw-mask-bottom-to-color
--tw-mask-bottom-to-position
--tw-mask-left
--tw-mask-left-from-color
--tw-mask-left-from-position
--tw-mask-left-to-color
--tw-mask-left-to-position
--tw-mask-linear
--tw-mask-linear-position
--tw-mask-linear-from-color
--tw-mask-linear-from-position
--tw-mask-linear-to-color
--tw-mask-linear-to-position
--tw-mask-radial
--tw-mask-radial-shape
--tw-mask-radial-size
--tw-mask-radial-position
--tw-mask-radial-from-color
--tw-mask-radial-from-position
--tw-mask-radial-to-color
--tw-mask-radial-to-position
--tw-mask-conic
--tw-mask-conic-position
--tw-mask-conic-from-color
--tw-mask-conic-from-position
--tw-mask-conic-to-color
--tw-mask-conic-to-position
box-decoration-break
background-size
background-attachment
background-clip
background-position
background-repeat
background-origin
mask-composite
mask-mode
mask-type
mask-size
mask-clip
mask-position
mask-repeat
mask-origin
fill
stroke
stroke-width
object-fit
object-position
padding
padding-inline
padding-block
padding-inline-start
padding-inline-end
padding-block-start
padding-block-end
padding-top
padding-right
padding-bottom
padding-left
text-align
text-indent
vertical-align
font-family
font-feature-settings
font-size
line-height
font-weight
letter-spacing
text-wrap
overflow-wrap
word-break
text-overflow
hyphens
white-space
tab-size
color
text-transform
font-style
font-stretch
font-variant-numeric
text-decoration-line
text-decoration-color
text-decoration-style
text-decoration-thickness
text-underline-offset
-webkit-font-smoothing
placeholder-color
caret-color
accent-color
color-scheme
opacity
background-blend-mode
mix-blend-mode
box-shadow
--tw-shadow
--tw-shadow-color
--tw-ring-shadow
--tw-ring-color
--tw-inset-shadow
--tw-inset-shadow-color
--tw-inset-ring-shadow
--tw-inset-ring-color
--tw-ring-offset-width
--tw-ring-offset-color
outline
outline-width
outline-offset
outline-color
--tw-blur
--tw-brightness
--tw-contrast
--tw-drop-shadow
--tw-grayscale
--tw-hue-rotate
--tw-invert
--tw-saturate
--tw-sepia
filter
--tw-backdrop-blur
--tw-backdrop-brightness
--tw-backdrop-contrast
--tw-backdrop-grayscale
--tw-backdrop-hue-rotate
--tw-backdrop-invert
--tw-backdrop-opacity
--tw-backdrop-saturate
--tw-backdrop-sepia
backdrop-filter
transition-property
transition-behavior
transition-delay
transition-duration
transition-timing-function
will-change
contain
content
forced-color-adjust`

// namedColors are CSS's color keywords.
const namedColors = `black
silver
gray
white
maroon
red
purple
fuchsia
green
lime
olive
yellow
navy
blue
teal
aqua
aliceblue
antiquewhite
aquamarine
azure
beige
bisque
blanchedalmond
blueviolet
brown
burlywood
cadetblue
chartreuse
chocolate
coral
cornflowerblue
cornsilk
crimson
cyan
darkblue
darkcyan
darkgoldenrod
darkgray
darkgreen
darkgrey
darkkhaki
darkmagenta
darkolivegreen
darkorange
darkorchid
darkred
darksalmon
darkseagreen
darkslateblue
darkslategray
darkslategrey
darkturquoise
darkviolet
deeppink
deepskyblue
dimgray
dimgrey
dodgerblue
firebrick
floralwhite
forestgreen
gainsboro
ghostwhite
gold
goldenrod
greenyellow
grey
honeydew
hotpink
indianred
indigo
ivory
khaki
lavender
lavenderblush
lawngreen
lemonchiffon
lightblue
lightcoral
lightcyan
lightgoldenrodyellow
lightgray
lightgreen
lightgrey
lightpink
lightsalmon
lightseagreen
lightskyblue
lightslategray
lightslategrey
lightsteelblue
lightyellow
limegreen
linen
magenta
mediumaquamarine
mediumblue
mediumorchid
mediumpurple
mediumseagreen
mediumslateblue
mediumspringgreen
mediumturquoise
mediumvioletred
midnightblue
mintcream
mistyrose
moccasin
navajowhite
oldlace
olivedrab
orange
orangered
orchid
palegoldenrod
palegreen
paleturquoise
palevioletred
papayawhip
peachpuff
peru
pink
plum
powderblue
rebeccapurple
rosybrown
royalblue
saddlebrown
salmon
sandybrown
seagreen
seashell
sienna
skyblue
slateblue
slategray
slategrey
snow
springgreen
steelblue
tan
thistle
tomato
turquoise
violet
wheat
whitesmoke
yellowgreen
transparent
currentcolor
canvas
canvastext
linktext
visitedtext
activetext
buttonface
buttontext
buttonborder
field
fieldtext
highlight
highlighttext
selecteditem
selecteditemtext
mark
marktext
graytext
accentcolor
accentcolortext`
