//go:build goesm

// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// goesm's patch of internal/strconv's ftoa.go: the decimal digits of a
// float64 come from the engine's Number formatting (ftoaDigits in
// runtime/src/natives.ts), which gives the same digits as ftoa64 does on
// uint64, a BigInt under goesm, many times faster. fmtEFG formats them as
// before; the Go code still handles what the engine cannot (float32, the
// 'b' and 'x' formats, zero, NaN, ±Inf, and precisions beyond 100 digits).
package strconv

// FormatFloat converts the floating-point number f to a string,
// according to the format fmt and precision prec. It rounds the
// result assuming that the original was obtained from a floating-point
// value of bitSize bits (32 for float32, 64 for float64).
func FormatFloat(f float64, fmt byte, prec, bitSize int) string {
	if bitSize == 32 {
		return string(ftoa32(make([]byte, 0, max(prec+4, 24)), float32(f), fmt, prec))
	}
	if bitSize == 64 {
		return string(ftoa64Digits(make([]byte, 0, max(prec+4, 24)), f, fmt, prec))
	}
	panic("strconv: illegal FormatFloat bitSize")
}

// AppendFloat appends the string form of the floating-point number f,
// as generated by [FormatFloat], to dst and returns the extended buffer.
func AppendFloat(dst []byte, f float64, fmt byte, prec, bitSize int) []byte {
	if bitSize == 32 {
		return ftoa32(dst, float32(f), fmt, prec)
	}
	if bitSize == 64 {
		return ftoa64Digits(dst, f, fmt, prec)
	}
	panic("strconv: illegal AppendFloat bitSize")
}

// ftoaBuf holds the digits of ftoa64Digits until fmtEFG has copied them:
// goesm runs one goroutine at a time, and neither yields.
var ftoaBuf = make([]byte, 128)

func ftoa64Digits(dst []byte, val float64, fmt byte, prec int) []byte {
	switch fmt {
	case 'e', 'E', 'f', 'g', 'G':
		dp, nd, ok := ftoaDigits(ftoaBuf, val, fmt, prec)
		if !ok {
			break
		}
		shortest := prec < 0
		if shortest {
			// Precision for shortest representation mode.
			switch fmt {
			case 'e', 'E':
				prec = max(nd-1, 0)
			case 'f':
				prec = max(nd-dp, 0)
			case 'g', 'G':
				prec = nd
			}
		} else if (fmt == 'g' || fmt == 'G') && prec == 0 {
			prec = 1
		}
		return fmtEFG(dst, val < 0, ftoaBuf, dp, nd, prec, fmt, shortest)
	}
	return ftoa64(dst, val, fmt, prec)
}

// ftoaDigits writes the decimal digits of val to buf: the shortest ones
// that read back as val if prec < 0, else val rounded (to even) to prec
// digits for fmt. It returns the decimal point position and the number of
// digits without trailing zeros, or ok == false for ftoa64 to do it.
func ftoaDigits(buf []byte, val float64, fmt byte, prec int) (dp, nd int, ok bool)
