//go:build goesm

// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// goesm's patch of internal/strconv's itoa.go: base 10 comes from the
// engine's number and BigInt formatting (formatDecimal and itoa in
// runtime/src/natives.ts) instead of formatBase10's arithmetic on uint64,
// a BigInt under goesm.
package strconv

// FormatUint returns the string representation of i in the given base,
// for 2 <= base <= 36. The result uses the lower-case letters 'a' to 'z'
// for digit values >= 10.
func FormatUint(i uint64, base int) string {
	if base == 10 {
		if i < nSmalls {
			return small(int(i))
		}
		return formatDecimal(i, false)
	}
	_, s := formatBits(nil, i, base, false, false)
	return s
}

// FormatInt returns the string representation of i in the given base,
// for 2 <= base <= 36. The result uses the lower-case letters 'a' to 'z'
// for digit values >= 10.
func FormatInt(i int64, base int) string {
	if base == 10 {
		if 0 <= i && i < nSmalls {
			return small(int(i))
		}
		u := uint64(i)
		if i < 0 {
			u = -u
		}
		return formatDecimal(u, i < 0)
	}
	_, s := formatBits(nil, uint64(i), base, i < 0, false)
	return s
}

// Itoa is equivalent to [FormatInt](int64(i), 10).
func Itoa(i int) string {
	if 0 <= i && i < nSmalls {
		return small(i)
	}
	return itoa(i)
}

// AppendUint appends the string form of the unsigned integer i,
// as generated by [FormatUint], to dst and returns the extended buffer.
func AppendUint(dst []byte, i uint64, base int) []byte {
	if base == 10 {
		if i < nSmalls {
			return append(dst, small(int(i))...)
		}
		return append(dst, formatDecimal(i, false)...)
	}
	dst, _ = formatBits(dst, i, base, false, true)
	return dst
}

// formatDecimal returns u in base 10, with a minus sign if neg.
func formatDecimal(u uint64, neg bool) string

// itoa returns i in base 10.
func itoa(i int) string
